[project]
name = "btc-prediction-market"
description = "Bitcoin-Anchored Prediction Market using Clarity 4"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.btc-prediction-market-v3]
path = "contracts/btc-prediction-market-v3.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
